# Configuration for 1900.com.vn
website:
  name: "1900.com.vn"
  base_url: "https://1900.com.vn/cong-ty-ve-nha-hang-khach-san-c209.html"
  industries_page: "https://1900.com.vn/cong-ty-ve-nha-hang-khach-san-c209.html"

xpath:
  # Industry selection
  industry_select: "//label[normalize-space()='Ngành']/following::span[contains(@class,'select2')][1]//span[contains(@class,'select2-selection')]"
  industry_select_fallback: "//span[@id='select2-career_category_id-container']/ancestor::span[contains(@class,'selection')]//span[contains(@class,'select2-selection')]"
  industry_results: "//ul[contains(@class,'select2-results__options')]"
  industry_search: "//input[contains(@class,'select2-search__field')]"
  industry_options: "//li[contains(@class,'select2-results__option') and not(contains(@class,'loading'))]"
  
  # Company details
  company_name: "//h1[contains(@class,'company-detail-name')]/span[1]"
  company_address: "//div[@class='box-body']//div[@class='item'][1]//div[@class='desc']"
  company_address_fallback: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Trụ sở')]]/span"
  company_website: "//div[@class='box-caption']/p//a[starts-with(@href,'http')]"
  company_phone: "//div[@class='box-caption']/p//a[starts-with(@href,'tel:')]"
  company_scale: "//div[contains(@class,'company-subdetail')]//div[contains(@class,'company-subdetail-info')][2]//span[2]"
  company_created_year: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Thành lập')]]/span"
  company_business: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Ngành')]]/a"
  company_revenue: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Doanh thu')]]/span"
  
  # Social media
  social_media_container: "//div[contains(@class,'social-media-container')]//a[contains(@href,'{platform}')]"
  
  # Pagination
  pagination_links: "//li[@class='page-item']//a[@class='page-link']"
  
  # Company links
  company_links: "a[href*='tong-quan']"
  
  # Filter button
  filter_button: "//div[contains(@class,'d-none')]//button[contains(@class,'btn-company')]"

crawl4ai:
  website_query: "Return only business emails found in Contact/About/Footer. Output exactly: valid emails separated by semicolons (e.g., email1@x.com; email2@y.vn). Domain not like jpg, png, gif, etc."
  facebook_query: "Return only business emails from Facebook About/Intro/Contact section. Output exactly: valid emails separated by semicolons (e.g., email1@x.com; email2@y.vn). Domain not like jpg, png, gif, etc."

processing:
  # batch_size: 30 (cũ)
  batch_size: 50  # Tăng từ 30 lên 50 - tận dụng CPU mạnh
  # write_batch_size: 150 (cũ)
  write_batch_size: 200  # Tăng từ 150 lên 200
  # max_concurrent_pages: 5 (cũ)
  max_concurrent_pages: 8  # Tăng từ 5 lên 8 - phù hợp 50% CPU
  max_retries: 5  # Giữ nguyên
  # delay_range: [3, 8] (cũ) - tăng từ [2,6] lên [3,8] - đợi lâu hơn
  delay_range: [2, 5]  # Giảm từ [3,8] xuống [2,5] - CPU mạnh xử lý nhanh
  # batch_delay: [6, 12] (cũ)
  batch_delay: [4, 8]  # Giảm từ [6,12] xuống [4,8]
  # session_delay: [12, 25] (cũ)
  session_delay: [8, 15]  # Giảm từ [12,25] xuống [8,15]
  timeout: 120000  # Tăng từ 90s lên 120s cho industry lớn
  network_timeout: 90000  # Tăng từ 60s lên 90s
  # page_load_wait: 2000 (cũ)
  page_load_wait: 1500  # Giảm từ 2000 xuống 1500
  # js_load_wait: 3000 (cũ)
  js_load_wait: 2000  # Giảm từ 3000 xuống 2000
  stealth_mode: true
  # Industry loading settings - đơn giản
  industry_load_timeout: 90000  # Tăng từ 60s lên 90s
  industry_scroll_timeout: 120000  # Tăng từ 90s lên 120s
  industry_retry_delay: 3  # Giữ nguyên
  # Email extraction settings - đơn giản và hiệu quả
  email_extraction_timeout: 90000  # Tăng từ 60s lên 90s - Facebook cần thời gian lâu
  email_retry_delay: [4, 8]  # Delay có jitter, cân bằng tốc độ/ổn định

output:
  output_dir: "data/tasks"
  final_output: "data/company_contacts.csv"
  log_file: "crawler.log"

fieldnames:
  - industry_name
  - name
  - address
  - website
  - phone
  - created_year
  - revenue
  - scale
  - link
  - facebook
  - linkedin
  - tiktok
  - youtube
  - instagram
  - extracted_emails
  - email_source
