# Configuration for 1900.com.vn
website:
  name: "1900.com.vn"
  base_url: "https://1900.com.vn/cong-ty-ve-nha-hang-khach-san-c209.html"
  industries_page: "https://1900.com.vn/cong-ty-ve-nha-hang-khach-san-c209.html"

xpath:
  # Industry selection
  industry_select: "//label[normalize-space()='Ngành']/following::span[contains(@class,'select2')][1]//span[contains(@class,'select2-selection')]"
  industry_select_fallback: "//span[@id='select2-career_category_id-container']/ancestor::span[contains(@class,'selection')]//span[contains(@class,'select2-selection')]"
  industry_results: "//ul[contains(@class,'select2-results__options')]"
  industry_search: "//input[contains(@class,'select2-search__field')]"
  industry_options: "//li[contains(@class,'select2-results__option') and not(contains(@class,'loading'))]"
  
  # Company details
  company_name: "//h1[contains(@class,'company-detail-name')]/span[1]"
  company_address: "//div[@class='box-body']//div[@class='item'][1]//div[@class='desc']"
  company_address_fallback: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Trụ sở')]]/span"
  company_website: "//div[@class='box-caption']/p//a[starts-with(@href,'http')]"
  company_phone: "//div[@class='box-caption']/p//a[starts-with(@href,'tel:')]"
  company_scale: "//div[contains(@class,'company-subdetail')]//div[contains(@class,'company-subdetail-info')][2]//span[2]"
  company_created_year: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Thành lập')]]/span"
  company_business: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Ngành')]]/a"
  company_revenue: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Doanh thu')]]/span"
  
  # Social media
  social_media_container: "//div[contains(@class,'social-media-container')]//a[contains(@href,'{platform}')]"
  
  # Pagination
  pagination_links: "//li[@class='page-item']//a[@class='page-link']"
  
  # Company links
  company_links: "a[href*='tong-quan']"
  
  # Filter button
  filter_button: "//div[contains(@class,'d-none')]//button[contains(@class,'btn-company')]"

crawl4ai:
  website_query: "Extract business emails from Contact Us/About/footer sections. The email should not start with number or uuid like, domain not like uuid or number or dash like uuid-number-dash. The email should be a valid email address. If any invalid email, return None."
  facebook_query: "Extract business emails from Facebook About/Intro/Contact sections. The email should not start with number or uuid like, domain not like uuid or number or dash like uuid-number-dash. The email should be a valid email address. If any invalid email, return None."

processing:
  batch_size: 30
  write_batch_size: 150
  max_concurrent_pages: 8
  max_retries: 2
  delay_range: [0.8, 2.0]
  timeout: 60000
  network_timeout: 20000

output:
  output_dir: "data/tasks"
  final_output: "data/company_contacts.csv"
  log_file: "crawler.log"

fieldnames:
  - industry_name
  - name
  - address
  - website
  - phone
  - created_year
  - revenue
  - scale
  - link
  - facebook
  - linkedin
  - tiktok
  - youtube
  - instagram
  - extracted_emails
  - email_source
