# Configuration for 1900.com.vn
website:
  name: "1900.com.vn"
  base_url: "https://1900.com.vn/cong-ty-ve-nha-hang-khach-san-c209.html"
  industries_page: "https://1900.com.vn/cong-ty-ve-nha-hang-khach-san-c209.html"

xpath:
  # Industry selection
  industry_select: "//label[normalize-space()='Ngành']/following::span[contains(@class,'select2')][1]//span[contains(@class,'select2-selection')]"
  industry_select_fallback: "//span[@id='select2-career_category_id-container']/ancestor::span[contains(@class,'selection')]//span[contains(@class,'select2-selection')]"
  industry_results: "//ul[contains(@class,'select2-results__options')]"
  industry_search: "//input[contains(@class,'select2-search__field')]"
  industry_options: "//li[contains(@class,'select2-results__option') and not(contains(@class,'loading'))]"
  
  # Company details
  company_name: "//h1[contains(@class,'company-detail-name')]/span[1]"
  company_address: "//div[@class='box-body']//div[@class='item'][1]//div[@class='desc']"
  company_address_fallback: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Trụ sở')]]/span"
  company_website: "//div[@class='box-caption']/p//a[starts-with(@href,'http')]"
  company_phone: "//div[@class='box-caption']/p//a[starts-with(@href,'tel:')]"
  company_scale: "//div[contains(@class,'company-subdetail')]//div[contains(@class,'company-subdetail-info')][2]//span[2]"
  company_created_year: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Thành lập')]]/span"
  company_industry: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Ngành')]]/a"
  company_revenue: "//ul[contains(@class,'company-details')]//li[label[contains(text(),'Doanh thu')]]/span"
  
  # Social media
  social_media_container: "//div[contains(@class,'social-media-container')]//a[contains(@href,'{platform}')]"
  
  # Pagination
  pagination_links: "//li[@class='page-item']//a[@class='page-link']"
  
  # Company links
  company_links: "a[href*='tong-quan']"
  
  # Filter button
  filter_button: "//div[contains(@class,'d-none')]//button[contains(@class,'btn-company')]"


crawl4ai:
  website_query: "Return only business emails found in Contact/About/Footer. Output exactly: valid emails separated by semicolons (e.g., email1@x.com; email2@y.vn). Domain not like jpg, png, gif, etc."
  facebook_query: "Return only business emails from Facebook About/Intro/Contact section. Output exactly: valid emails separated by semicolons (e.g., email1@x.com; email2@y.vn). Domain not like jpg, png, gif, etc."
  
  # BestFirstCrawlingStrategy Configuration
  max_depth: 1                    # Maximum crawling depth
  max_pages: 3                   # Maximum number of pages to crawl
  include_external: false         # Include external links
  scorer_weight: 0.7              # Weight for keyword relevance scoring
  
  # Email-related keywords for scoring
  email_keywords:
    website:
      - "contact"
      - "email" 
      - "mail"
      - "lien he"
      - "lienhe"
      - "about"
      - "gioi thieu"
      - "info"
      - "support"
      - "help"
      - "reach"
      - "get in touch"
      - "connect"
    facebook:
      - "about"
      - "contact"
      - "email"
      - "mail"
      - "info"
      - "business"
      - "company"
      - "lien he"
      - "lienhe"
      - "thong tin"
      - "thongtin"


processing:
  # OPTIMIZED SETTINGS FOR BETTER PERFORMANCE
  batch_size: 100   # Tăng từ 50 lên 75 - tối ưu throughput
  write_batch_size: 300  # Tăng từ 200 lên 300 - giảm I/O overhead
  max_concurrent_pages: 6  # Tăng từ 5 lên 6 - tận dụng CPU tốt hơn
  max_retries: 5  # Giữ nguyên
  delay_range: [1.5, 4]  # Giảm từ [2,5] xuống [1.5,4] - tăng tốc độ
  batch_delay: [3, 6]  # Giảm từ [4,8] xuống [3,6] - tăng throughput
  session_delay: [6, 12]  # Giảm từ [8,15] xuống [6,12] - tăng tốc độ
  timeout: 180000  # Tăng lên 3 phút để tránh timeout
  network_timeout: 120000  # Tăng lên 2 phút để tránh browser đóng
  # page_load_wait: 2000 (cũ)
  page_load_wait: 1500  # Giảm từ 2000 xuống 1500
  # js_load_wait: 3000 (cũ)
  js_load_wait: 2000  # Giảm từ 3000 xuống 2000
  stealth_mode: true
  # Industry loading settings - đơn giản
  industry_load_timeout: 180000  # Tăng lên 3 phút
  industry_scroll_timeout: 240000  # Tăng lên 4 phút
  industry_retry_delay: 3  # Giữ nguyên
  industry_wave_size: 4
  # Email extraction settings - đơn giản và hiệu quả
  email_extraction_timeout: 30000  # Giảm từ 90s xuống 30s - batch size cao
  email_retry_delay: [4, 8]  # Delay có jitter, cân bằng tốc độ/ổn định
  # Deep crawling settings
  website_deep_paths:
    - "/contact"
    - "/contact-us"
    - "/lien-he"
    - "/lienhe"
    - "/about"
    - "/about-us"
    - "/gioi-thieu"
  facebook_about_variants:
    - "?sk=about"
    - "/about"

output:
  output_dir: "data/tasks"
  final_output: "data/company_contacts.csv"
  log_file: "crawler.log"

fieldnames:
  - industry_name
  - name
  - address
  - website
  - phone
  - created_year
  - revenue
  - scale
  - link
  - facebook
  - linkedin
  - tiktok
  - youtube
  - instagram
  - extracted_emails
  - email_source
